# Generated by Django 5.0.6 on 2025-03-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotingApp', '0003_candidate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='course_of_study',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='level',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='matric_number',
            field=models.CharField(default='Unknown', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='state_of_origin',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
