# Generated by Django 5.0.6 on 2025-03-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotingApp', '0004_candidate_course_of_study_candidate_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='matric_number',
        ),
        migrations.AddField(
            model_name='candidate',
            name='matric',
            field=models.CharField(blank=True, default='Unknown', max_length=20, null=True, unique=True),
        ),
    ]
